### ISSUE TITLE
validation / core - Missing Translation(s)

### ISSUE THREAD

**Issue by cagatayldzz** [Extum/flarum-ext-turkish#8]
### validation
https://github.com/flarum/flarum-ext-english/blob/master/locale/validation.yml#L30-L39
https://github.com/flarum/flarum-ext-english/blob/master/locale/validation.yml#L45-L46
https://github.com/flarum/flarum-ext-english/blob/master/locale/validation.yml#L48-L57

### core
https://github.com/flarum/flarum-ext-english/blob/master/locale/core.yml#L22-L23
https://github.com/flarum/flarum-ext-english/blob/master/locale/core.yml#L30
https://github.com/flarum/flarum-ext-english/blob/master/locale/core.yml#L54-L56

**Comment by TurboProgramming** [comment]
Daha üzerinde çalışıyorum eksik olması normal eksikleri bildirmek sonra mantıklı olur. Yine de teşekkürler 👍

**Comment by cagatayldzz** [comment]
@TurboProgramming Genel olarak 2-3 dosyada kapsamlı bir kelime ekleme ve silme söz konusu. Diğerlerinde ufak kelime hataları mevcut onlarıda pc olduğum bir vakit pr olarak yapacağım.
