### ISSUE TITLE
Wrong Translation(s)

### ISSUE THREAD

**Issue by cagatayldzz** [Extum/flarum-ext-turkish#9]
https://github.com/Extum/flarum-ext-turkish/blob/master/locale/flarum-tags.yml#L49
> about_tags_text: "Etiketler konuları kategorize etmek için kullanılır. Birincil anahtar klasik kategoriler gibi düşünülebilir ve iki seviyeli olarak kullanılabilir. İkincil etiketlerin hiyerarşik bir devamı yoktur alt kategoriler olarak kullanılır."

---

https://github.com/Extum/flarum-ext-turkish/blob/master/locale/flarum-approval.yml#L12
> approve_posts_label: Yazıyı onayla

---

https://github.com/Extum/flarum-ext-turkish/blob/master/locale/core.yml#L119
> appearance_text: "Sitenizin görünümünü değiştirin"

---

https://github.com/Extum/flarum-ext-turkish/blob/master/locale/core.yml#L187
> text: Şifrenizi değiştirmek için aşağıdaki butona tıklayarak eposta adresinizi kontrol ediniz.

**Comment by TurboProgramming** [comment]
PR?
